### ISSUE TITLE
0.3.0 version break Carbon-D

### ISSUE THREAD

**Issue by imzhaodong** [atilaneves/mirror#27]
I found if I upgrade mirror library version from 0.2.1 to 0.3.0, it will break Carbon-D project. I have checked the code into Carbon-D project branch bug12_mirror_030.
In short autowrap will not be able to wrap below two lines if upgraded mirror lib.

```d
   alias CarbonRedisClient = from!"symmetry.carbon.redis_adapter".CarbonRedisClient;
   alias RabbitClient = from!"symmetry.api.rabbitmq.wrap".RabbitClient;
```

You can switch between 0.2.1 and 0.3.0 to see the issue. When use 0.3.0, compile/link is OK. When load it into Python, it will run into undefined symbol error for below symbol:

```
python.raw._object* python.type.callDlangFunction!(python.type.PythonType!(symmetry.api.rabbitmq.bindings.amqp_frame_t.Payload).PythonType._py_new(python.raw._typeobject*, python.raw._object*, python.raw._object*).__lambda4().impl(symmetry.api.rabbitmq.bindings.amqp_method_t, symmetry.api.rabbitmq.bindings.amqp_frame_t.Payload.Properties, symmetry.api.rabbitmq.bindings.amqp_bytes_t, symmetry.api.rabbitmq.bindings.amqp_frame_t.Payload.ProtocolHeader), std.typecons.Tuple!(symmetry.api.rabbitmq.bindings.amqp_method_t, symmetry.api.rabbitmq.bindings.amqp_frame_t.Payload.Properties, symmetry.api.rabbitmq.bindings.amqp_bytes_t, symmetry.api.rabbitmq.bindings.amqp_frame_t.Payload.ProtocolHeader).Tuple).callDlangFunction(ref std.typecons.Tuple!(symmetry.api.rabbitmq.bindings.amqp_method_t, symmetry.api.rabbitmq.bindings.amqp_frame_t.Payload.Properties, symmetry.api.rabbitmq.bindings.amqp_bytes_t, symmetry.api.rabbitmq.bindings.amqp_frame_t.Payload.ProtocolHeader).Tuple)
```

**Comment by atilaneves** [comment]
I can't reproduce this at all, at least not in the version of SIL I'm using, and I don't want to update right now because of all the problems caused by moving repo URLs.

**Comment by imzhaodong** [comment]
I think it's because we need below code to make it compile, at first I do not realize this. Maybe I can just close the issue then?
version(PyNIH) {
  private void hack0() {
      import symmetry.carbon.auth: Env;
      import python.type: PythonMethod;
      auto ptr = &PythonMethod!(Env, Env.name)._py_method_impl;
  }

  private void hack1() {
      import python.conv.d_to_python: toPython;
      import symmetry.api.rabbitmq.bindings: amqp_frame_t;
      auto _ = amqp_frame_t.Payload.init.toPython;
  }
}
